version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-php${PHP_VER}
    image: ${DOCKER_NAME}/apache-php${PHP_VER}
    container_name: ${CONTAINER_NAME}-apache
    volumes:
      - ${WEB_FOLDER}:/var/www
    ports:
      - 8080:80
      - 8083:443
    restart: always
    environment:
      APACHE_DOCUMENT_ROOT: ${WEB_ROOT}
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}

  node:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    image: ${DOCKER_NAME}/nodejs
    container_name: ${CONTAINER_NAME}-nodejs
    volumes:
      - ${NODEJS_FOLDER}:/usr/src/app
    ports:
      - 8082:8080
      - 8888:443

  db:
    image: mysql:5.7
    container_name: ${CONTAINER_NAME}-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_NAME}-phpmyadmin
    environment:
      - PMA_HOST=db
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
